[package]
name = "nuked-opn2-rs"
version = "0.1.0"
authors = ["ShinySaana <shinysaana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuked-opn2-sys = { path = "../nuked-opn2-sys" }
