name: Node

on:
  release:
    types: ["published"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - run: "npm build build:linux:x86"
    - run: "npm build build:linux:x64"
    
