name: Node

on:
  release:
    types: ["published"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - run: "rustup target add "

    - run: "npm install --ignore-scripts"
      working-directory: ./nuked-opn2-node
    
    
    - run: "npm run build:linux:x86"
      working-directory: ./nuked-opn2-node
    - run: "npm run build:linux:x64"
      working-directory: ./nuked-opn2-node
    
